check chain_name

diff --git a/.github/workflows/validate_assetlistjson.yml b/.github/workflows/validate_assetlistjson.yml
--- a/.github/workflows/validate_assetlistjson.yml
+++ b/.github/workflows/validate_assetlistjson.yml
@@ -11,10 +11,22 @@ jobs:
       - name: Install JSON-Schema-Validator
         run: npm install -g jsonschema
 
-      - name: Validate Assetlist.json schema
+      - name: Validate assetlist.json schema
         run: |
-          for file in $(find . -name 'assetlist.json' | grep -v '_template/'); do
-            if ! jsonschema -i "$file" ./assetlist.schema.json; then
+          json_files=($(find . -name 'assetlist.json' | grep -v '_template/'))
+          all_names=()
+          for json_file in "${json_files[@]}"; do
+            # Validate schema
+            if ! jsonschema -i "$json_file" ./assetlist.schema.json; then
+              echo "Schema validation failed for $json_file"
               exit 1
             fi
+            # Check for duplicate chain names
+            chain_name=$(jq -r '.chain_name' "$json_file")
+            if [[ " ${all_names[@]} " =~ " ${chain_name} " ]]; then
+              echo "Duplicate chain_name found: ${chain_name} in file ${json_file}"
+              exit 1
+            fi
+            all_names+=("$chain_name")
           done
+          echo "No duplicates found. All assetlist.json files are valid."
